In [63]:
from tensorflow.keras.layers import TextVectorization
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [12]:
# Example training data, of dtype `string`.
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample."]])

In [13]:
training_data
# Create a TextVectorization layer instance. It can be configured to either
# return integer token indices, or a dense token representation (e.g. multi-hot
# or TF-IDF). The text standardization and text splitting algorithms are fully
# configurable.

array([['This is the 1st sample.'],
       ["And here's the 2nd sample."]], dtype='<U26')

In [44]:
vectorizer = TextVectorization(output_mode="binary", ngrams=2)

# Calling `adapt` on an array or dataset makes the layer generate a vocabulary
# index for the data, which can then be reused when seeing new data.
vectorizer.adapt(training_data)

In [45]:
vectorizer.get_vocabulary()

['[UNK]',
 'the',
 'sample',
 'this is',
 'this',
 'the 2nd',
 'the 1st',
 'is the',
 'is',
 'heres the',
 'heres',
 'and heres',
 'and',
 '2nd sample',
 '2nd',
 '1st sample',
 '1st']

In [46]:
# After calling adapt, the layer is able to encode any n-gram it has seen before
# in the `adapt()` data. Unknown n-grams are encoded via an "out-of-vocabulary"
# token.
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[0. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]], shape=(2, 17), dtype=float32)


In [48]:
integer_data.numpy().shape

(2, 17)

In [49]:
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

In [62]:
#Layers

from tensorflow.keras import layers
from tensorflow.keras import activations

In [64]:
foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
foo

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-10.,  -5.,   0.,   5.,  10.], dtype=float32)>

In [75]:
tf.keras.activations.relu(foo, threshold=-6)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-0., -5.,  0.,  5., 10.], dtype=float32)>

In [77]:
tf.keras.activations.sigmoid(foo)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([4.539787e-05, 6.692851e-03, 5.000000e-01, 9.933072e-01,
       9.999546e-01], dtype=float32)>

In [84]:
inputs = tf.random.normal(shape=(2, 3))
output = tf.keras.activations.softmax(inputs, axis=-1)
# inputs
output

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.06187875, 0.07020846, 0.86791277],
       [0.01577533, 0.13397506, 0.8502495 ]], dtype=float32)>

In [85]:
layer = tf.keras.layers.Dense(32, activation=tf.keras.activations.softmax)

In [89]:
#Poolings
x = tf.constant([1., 2., 3., 4., 5.])
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [93]:
x = tf.reshape(x, [1, 5, 1])
x

<tf.Tensor: shape=(1, 5, 1), dtype=float32, numpy=
array([[[1.],
        [2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [103]:
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=2,strides=1, padding='valid')

In [104]:
max_pool_1d(x)

<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [105]:
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=2,strides=1, padding='valid')

In [117]:
x = tf.constant([[1., 2., 3.], [4., 5., 6.],[7., 8., 9.]])

In [118]:
x = tf.reshape(x, [1, 3, 3, 1])
x

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)>

In [110]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid')

In [111]:
max_pool_2d(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[5.],
         [6.]],

        [[8.],
         [9.]]]], dtype=float32)>

In [112]:
input_shape = (2, 4, 5, 3)
x = tf.random.normal(input_shape)
x

<tf.Tensor: shape=(2, 4, 5, 3), dtype=float32, numpy=
array([[[[ 1.151908  ,  0.73197025,  0.60676116],
         [-0.7270176 , -1.0644354 , -0.7019978 ],
         [-1.3141625 ,  0.35292605, -0.2118673 ],
         [ 0.7213064 ,  2.4865227 , -0.69563836],
         [-0.7972146 ,  0.7661949 ,  0.25465742]],

        [[ 1.161866  ,  1.0511738 ,  1.2748348 ],
         [ 0.9310628 , -1.3338273 ,  1.7616367 ],
         [-0.30589047,  0.93164253, -0.5975304 ],
         [ 0.9608474 ,  1.0251048 , -1.0439398 ],
         [-0.9179695 , -0.37616038, -0.7189862 ]],

        [[ 0.95430464, -0.86915636, -0.88413996],
         [-0.43447548,  0.65850645, -1.2216039 ],
         [ 0.26395795, -0.5973517 ,  0.80025613],
         [-1.5184633 , -0.38722223,  0.86517745],
         [ 0.03613742,  0.9416531 ,  1.8126674 ]],

        [[ 0.7236268 , -0.54822224, -1.6190277 ],
         [ 1.7952847 ,  0.48501176,  0.8191651 ],
         [-0.19737953,  0.52802294,  1.9227908 ],
         [ 1.5114888 ,  0.663335  ,  0.2

In [123]:
y = tf.keras.layers.GlobalMaxPool2D()(x)
y

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[9.]], dtype=float32)>

In [115]:
y.shape

TensorShape([2, 3])