In [59]:
import tensorflow as tf
import numpy as np
import time

In [4]:
q = tf.Variable([[True, False], [True, False]])
r = tf.Variable([[True, True], [False, True]])
p=tf.math.logical_and(q,r)
print(p)

tf.Tensor(
[[ True False]
 [False False]], shape=(2, 2), dtype=bool)


In [7]:
p = tf.Variable(np.random.randn(1,64))

In [10]:
p = tf.Variable(np.random.randn(1,64))
reshaped_p = tf.reshape(p, (8,8,1))
reshaped_p

<tf.Tensor: shape=(8, 8, 1), dtype=float64, numpy=
array([[[-3.27146262e-02],
        [-2.36778051e-03],
        [ 1.09687288e-01],
        [ 1.22593401e+00],
        [ 8.59782850e-01],
        [ 4.93691728e-01],
        [-3.90356885e-01],
        [-6.97547359e-01]],

       [[-2.33716030e-01],
        [ 7.19057999e-01],
        [ 2.05338700e-02],
        [ 1.32529227e+00],
        [-1.29420661e+00],
        [ 1.72325952e-01],
        [ 4.55883695e-01],
        [ 4.29423382e-01]],

       [[ 2.56212135e-01],
        [-4.11511116e-01],
        [ 8.11033955e-01],
        [-1.86764532e-01],
        [ 8.58248269e-01],
        [-1.32094937e+00],
        [-6.29977263e-02],
        [-1.39747142e+00]],

       [[ 3.89692217e-01],
        [-4.14769181e-01],
        [-1.80376311e+00],
        [-7.84547056e-01],
        [ 1.75454114e+00],
        [-1.29009014e-03],
        [-8.31556109e-01],
        [ 7.77392016e-01]],

       [[-1.22913522e-02],
        [-1.87520510e+00],
        [-8.06817846e-0

In [15]:
reshaped_p.ndim

3

In [16]:
#Computational graph

In [21]:
#Automatic differentiation
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = 3.0 * tf.math.log(x)

dy_dx = tape.gradient(y, x) # dy/dx = 3.0 * 1/x
print('Gradient dy_dx:', dy_dx)

Gradient dy_dx: tf.Tensor(1.0, shape=(), dtype=float32)


In [23]:
#What is the slope of the curve y=3x3+5x2−3x+10 at x=−2? 

#Automatic differentiation
x = tf.Variable(-2.0)

with tf.GradientTape() as tape:
    y = 3.0 * (x ** 3) + 5 * (x ** 2) - 3 * x + 10

dy_dx = tape.gradient(y, x) # dy/dx = 3.0 * 1/x
print('Gradient dy_dx:', dy_dx)

Gradient dy_dx: tf.Tensor(13.0, shape=(), dtype=float32)


In [28]:
#Consider the function given below: y=30.2x+5x2−log(x)+tanh(x)
#Using TensorFlow, at x=10, find out whether the function is increasing or decreasing.

#Automatic differentiation
x = tf.Variable(10.0)

with tf.GradientTape() as tape:
    y = 3.0 ** (0.2*x) + 5 * (x ** 2) - tf.math.log(x) + tf.math.tanh(x)

dy_dx = tape.gradient(y, x) # dy/dx = 3.0 * 1/x
print('Gradient dy_dx:', dy_dx)

Gradient dy_dx: tf.Tensor(101.8775, shape=(), dtype=float32)


In [30]:
#For multivariate functions, gradients are partial derivatives

x = tf.Variable(3.0)
y = tf.Variable(4.0)


with tf.GradientTape() as tape:
    r = x ** 2 + y ** 2
dr_dx, dr_dy = tape.gradient(r, [x,y])
print('Gradient dr_dx:', dr_dx.numpy()) #2x
print('Gradient dr_dy:', dr_dy.numpy()) #2y

Gradient dr_dx: 6.0
Gradient dr_dy: 8.0


In [35]:
#It also supports chain rule of differentiation

x = tf.Variable(3.0)


with tf.GradientTape() as tape:
    y = x ** 2
    r = y ** 2
dr_dx= tape.gradient(r, x)
print('Gradient dr_dx:', dr_dx.numpy())

Gradient dr_dx: 108.0


In [42]:
#To calculate the derivative of intermidiate variables wrt x we need add persistence = True parameter in the context
x = tf.Variable(5.0)


with tf.GradientTape(persistent=True) as tape:
    t = tf.math.sqrt(((x ** 0.3) + 0.1))
    p = tf.math.exp(4 * t)
    q = p ** 2 - 4 * p
dp_dx = tape.gradient(p, x)
dq_dx = tape.gradient(q, x)
print('Gradient dp_dx:', dp_dx.numpy()) #2x
print('Gradient dq_dx:', dq_dx.numpy()) #2y

Gradient dp_dx: 28.167446
Gradient dq_dx: 10590.19


In [56]:
#Minimising Functions
# Find the minima of the function y = x ^ 2 - 4

#Step 1: Initialize x
x = tf.Variable(tf.random.normal((1,)))
print('Initial value of x:', x)

Initial value of x: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.4420943], dtype=float32)>


In [58]:
#initial value of y
y_prev = x ** 2 - 4
print('Initial value of yprev:', y)

Initial value of yprev: tf.Tensor(9.0, shape=(), dtype=float32)


In [64]:
num_iters = []
x_values = []
y_values = []

lr = tf.constant(0.1)
tolerance = 1

#Step 2: loop the gradient descent
i = 0
while True:
    i += 1
    num_iters.append(i)
    print('x, yprev:',x.numpy(), y_prev.numpy())
    with tf.GradientTape() as tape:
        y = x ** 2 - 4
    dy_dx = tape.gradient(y, x)
    x.assign(x - lr * dy_dx)
    ynew = x ** 2 - 4
    
    print('x, ynew:',x.numpy(), ynew.numpy())
    x_values.append(x.numpy()[0])
    y_values.append(y.numpy()[0])
    
    delta = tf.abs((ynew - y_prev)*100./y_prev).numpy()[0]
    
    
    if delta <= tolerance:
        print('Exiting loop')
        break
    else:
        y_prev = ynew
        time.sleep(1)

x, yprev: [0.2857922] [-3.8045526]
x, ynew: [0.22863376] [-3.9477265]
x, yprev: [0.22863376] [-3.9477265]
x, ynew: [0.18290702] [-3.966545]
Exiting loop


In [65]:
import time
import tensorflow as tf
 
x = tf.Variable(tf.random.normal((1,)))
print("Initial value of x:", x.numpy()[0])
 
yprev = 7 *x ** 2 - 4 * x + 10.
print("Initial value of y using initial value of x:", yprev.numpy()[0])
 
iteration = 10
lr = 0.1
 
i = 0
for i in range(iteration):
  i += 1
 
  with tf.GradientTape() as tape:
    y = 7 *x ** 2 - 4 * x + 10.
  
  dy_dx = tape.gradient(y, x)
  x.assign(x - lr * dy_dx) 
 
  ynew = 7 *x ** 2 - 4 * x + 10.
 
  print("x, ynew:", x.numpy()[0], ynew.numpy()[0])
  
  yprev = ynew
  time.sleep(1)

Initial value of x: 0.5123543
Initial value of y using initial value of x: 9.788132
x, ynew: 0.19505829 9.486101
x, ynew: 0.32197672 9.437777
x, ynew: 0.2712093 9.430044
x, ynew: 0.29151627 9.428807
x, ynew: 0.2833935 9.428609
x, ynew: 0.2866426 9.428577
x, ynew: 0.28534293 9.428573
x, ynew: 0.28586283 9.428572
x, ynew: 0.28565487 9.428572
x, ynew: 0.28573805 9.428572
